const RECIPES = [
  {
    id: "masala-poha",
    name: "Masala Poha",
    emoji: "🍚",
    description: "Light, fluffy flattened rice tempered with mustard seeds, onions and peanuts.",
    servings: 2,
    time: "20 min",
    difficulty: "Easy",
    ingredients: [
      { name: "Thick poha (flattened rice)", quantity: "1.5 cups" },
      { name: "Onion", quantity: "1 medium, finely chopped" },
      { name: "Raw peanuts", quantity: "3 tbsp" },
      { name: "Green chilli", quantity: "1, slit" },
      { name: "Mustard seeds", quantity: "1 tsp" },
      { name: "Curry leaves", quantity: "8–10" },
      { name: "Turmeric powder", quantity: "1/2 tsp" },
      { name: "Sugar", quantity: "1 tsp" },
      { name: "Salt", quantity: "to taste" },
      { name: "Oil", quantity: "2 tbsp" },
      { name: "Lemon", quantity: "1/2" },
      { name: "Fresh coriander", quantity: "2 tbsp, chopped" },
    ],
    steps: [
      { ingredient: "Poha (flattened rice)", quantity: "1.5 cups", placement: "In a colander / strainer", action: "Rinse gently under water twice, then leave to drain and soften. Do not oversoak.", duration: "2 min" },
      { ingredient: "Oil", quantity: "2 tbsp", placement: "Into a heated pan on medium flame", action: "Let the oil warm up until it shimmers.", duration: "1 min" },
      { ingredient: "Mustard seeds", quantity: "1 tsp", placement: "Into the hot oil", action: "Wait until they crackle and pop.", duration: "30 sec" },
      { ingredient: "Raw peanuts", quantity: "3 tbsp", placement: "Into the pan", action: "Fry, stirring often, until golden and crunchy.", duration: "2 min" },
      { ingredient: "Curry leaves + green chilli", quantity: "8–10 leaves + 1 chilli", placement: "Into the pan", action: "Stir for a few seconds until fragrant.", duration: "20 sec" },
      { ingredient: "Onion", quantity: "1 medium", placement: "Into the pan", action: "Sauté until soft and translucent.", duration: "3 min" },
      { ingredient: "Turmeric + salt + sugar", quantity: "1/2 tsp + to taste + 1 tsp", placement: "Sprinkle over the onions", action: "Mix well so the spices coat everything evenly.", duration: "30 sec" },
      { ingredient: "Softened poha", quantity: "All of it", placement: "Into the pan", action: "Fold gently until evenly coated and heated through. Cover for a minute.", duration: "2 min" },
      { ingredient: "Lemon juice + coriander", quantity: "1/2 lemon + 2 tbsp", placement: "Over the finished poha", action: "Squeeze the lemon, scatter coriander and give a final gentle toss.", duration: "30 sec" },
    ],
  },
  {
    id: "masala-chai",
    name: "Masala Chai",
    emoji: "☕",
    description: "Strong spiced Indian tea simmered with milk, ginger and cardamom.",
    servings: 2,
    time: "10 min",
    difficulty: "Easy",
    ingredients: [
      { name: "Water", quantity: "1 cup" },
      { name: "Milk", quantity: "1 cup" },
      { name: "Black tea leaves", quantity: "2 tsp" },
      { name: "Fresh ginger", quantity: "1 inch, crushed" },
      { name: "Green cardamom", quantity: "2 pods, crushed" },
      { name: "Sugar", quantity: "2 tsp (to taste)" },
    ],
    steps: [
      { ingredient: "Water", quantity: "1 cup", placement: "Into a saucepan on medium-high flame", action: "Bring to a gentle boil.", duration: "2 min" },
      { ingredient: "Ginger + cardamom", quantity: "1 inch + 2 pods", placement: "Into the boiling water", action: "Simmer so the spices release their aroma.", duration: "2 min" },
      { ingredient: "Black tea leaves", quantity: "2 tsp", placement: "Into the pan", action: "Boil until the water turns deep reddish-brown.", duration: "1 min" },
      { ingredient: "Milk", quantity: "1 cup", placement: "Pour into the pan", action: "Let it come to a boil, watching so it doesn't overflow.", duration: "2 min" },
      { ingredient: "Sugar", quantity: "2 tsp", placement: "Into the simmering chai", action: "Stir to dissolve, then simmer for a stronger brew.", duration: "1 min" },
      { ingredient: "The chai", quantity: "All of it", placement: "Through a strainer into cups", action: "Strain out the leaves and spices and serve hot.", duration: "30 sec" },
    ],
  },
  {
    id: "aloo-paratha",
    name: "Aloo Paratha",
    emoji: "🫓",
    description: "Whole-wheat flatbread stuffed with spiced mashed potato, cooked golden on a griddle.",
    servings: 3,
    time: "40 min",
    difficulty: "Medium",
    ingredients: [
      { name: "Whole wheat flour", quantity: "2 cups" },
      { name: "Water", quantity: "~3/4 cup" },
      { name: "Potatoes", quantity: "3 medium, boiled & mashed" },
      { name: "Green chilli", quantity: "1, finely chopped" },
      { name: "Coriander", quantity: "3 tbsp, chopped" },
      { name: "Cumin powder", quantity: "1 tsp" },
      { name: "Red chilli powder", quantity: "1/2 tsp" },
      { name: "Garam masala", quantity: "1/2 tsp" },
      { name: "Salt", quantity: "to taste" },
      { name: "Ghee or oil", quantity: "3 tbsp" },
    ],
    steps: [
      { ingredient: "Flour + water", quantity: "2 cups + ~3/4 cup", placement: "In a large mixing bowl", action: "Knead into a soft, smooth dough. Cover and rest.", duration: "10 min" },
      { ingredient: "Mashed potato + spices", quantity: "3 potatoes + all spices", placement: "In a separate bowl", action: "Mix potato with chilli, coriander, cumin, chilli powder, garam masala and salt into a smooth filling.", duration: "3 min" },
      { ingredient: "Dough", quantity: "1 lemon-sized ball", placement: "On a floured surface", action: "Roll into a small disc about 4 inches wide.", duration: "1 min" },
      { ingredient: "Potato filling", quantity: "2 tbsp", placement: "In the centre of the disc", action: "Gather the edges over the filling, seal, and flatten gently.", duration: "1 min" },
      { ingredient: "Stuffed ball", quantity: "1", placement: "On the floured surface", action: "Roll out carefully into a 7-inch paratha without tearing.", duration: "2 min" },
      { ingredient: "Paratha", quantity: "1", placement: "Onto a hot griddle (tawa)", action: "Cook until light brown spots appear, then flip.", duration: "1 min" },
      { ingredient: "Ghee or oil", quantity: "1 tsp", placement: "Brush over both sides", action: "Press edges and cook each side until golden and crisp.", duration: "2 min" },
    ],
  },
  {
    id: "veg-pulao",
    name: "Vegetable Pulao",
    emoji: "🍛",
    description: "Fragrant basmati rice cooked with whole spices and mixed vegetables.",
    servings: 4,
    time: "35 min",
    difficulty: "Medium",
    ingredients: [
      { name: "Basmati rice", quantity: "1.5 cups" },
      { name: "Mixed vegetables (carrot, beans, peas)", quantity: "1.5 cups" },
      { name: "Onion", quantity: "1, sliced" },
      { name: "Ginger-garlic paste", quantity: "1 tbsp" },
      { name: "Bay leaf", quantity: "1" },
      { name: "Cinnamon stick", quantity: "1 inch" },
      { name: "Cloves", quantity: "3" },
      { name: "Green cardamom", quantity: "2" },
      { name: "Cumin seeds", quantity: "1 tsp" },
      { name: "Water", quantity: "3 cups" },
      { name: "Salt", quantity: "to taste" },
      { name: "Ghee or oil", quantity: "2 tbsp" },
    ],
    steps: [
      { ingredient: "Basmati rice", quantity: "1.5 cups", placement: "In a bowl of water", action: "Rinse until water runs clear, then soak.", duration: "15 min" },
      { ingredient: "Ghee or oil", quantity: "2 tbsp", placement: "Into a heated pot on medium flame", action: "Warm until it shimmers.", duration: "1 min" },
      { ingredient: "Whole spices + cumin", quantity: "Bay leaf, cinnamon, cloves, cardamom, 1 tsp cumin", placement: "Into the hot ghee", action: "Sauté until fragrant and the cumin sizzles.", duration: "30 sec" },
      { ingredient: "Onion", quantity: "1 sliced", placement: "Into the pot", action: "Fry until soft and light golden.", duration: "3 min" },
      { ingredient: "Ginger-garlic paste", quantity: "1 tbsp", placement: "Into the pot", action: "Sauté until the raw smell disappears.", duration: "1 min" },
      { ingredient: "Mixed vegetables", quantity: "1.5 cups", placement: "Into the pot", action: "Stir-fry so they pick up the spice flavour.", duration: "3 min" },
      { ingredient: "Drained rice", quantity: "1.5 cups", placement: "Into the pot", action: "Fold in gently for a minute to coat the grains.", duration: "1 min" },
      { ingredient: "Water + salt", quantity: "3 cups + to taste", placement: "Pour into the pot", action: "Bring to a boil, then cover and cook on low until water is absorbed.", duration: "15 min" },
      { ingredient: "The pulao", quantity: "All of it", placement: "Rest covered, off the heat", action: "Let it steam, then fluff gently with a fork before serving.", duration: "5 min" },
    ],
  },
  {
    id: "scrambled-eggs",
    name: "Creamy Scrambled Eggs",
    emoji: "🍳",
    description: "Soft, buttery scrambled eggs — a quick and universal breakfast.",
    servings: 1,
    time: "8 min",
    difficulty: "Easy",
    ingredients: [
      { name: "Eggs", quantity: "3" },
      { name: "Butter", quantity: "1 tbsp" },
      { name: "Milk", quantity: "2 tbsp" },
      { name: "Salt", quantity: "a pinch" },
      { name: "Black pepper", quantity: "a pinch" },
      { name: "Chives (optional)", quantity: "1 tbsp, chopped" },
    ],
    steps: [
      { ingredient: "Eggs + milk", quantity: "3 eggs + 2 tbsp", placement: "In a bowl", action: "Whisk together until smooth and slightly frothy.", duration: "1 min" },
      { ingredient: "Salt + pepper", quantity: "a pinch each", placement: "Into the egg mixture", action: "Whisk again to season evenly.", duration: "15 sec" },
      { ingredient: "Butter", quantity: "1 tbsp", placement: "Into a non-stick pan on low heat", action: "Melt gently without letting it brown.", duration: "1 min" },
      { ingredient: "Egg mixture", quantity: "All of it", placement: "Pour into the pan", action: "Let it sit briefly, then stir slowly and constantly.", duration: "2 min" },
      { ingredient: "The eggs", quantity: "All of it", placement: "Still in the pan", action: "Remove from heat while slightly wet — they finish cooking off the flame.", duration: "30 sec" },
      { ingredient: "Chives", quantity: "1 tbsp", placement: "Over the plated eggs", action: "Scatter on top and serve immediately.", duration: "15 sec" },
    ],
  },
  {
    id: "fluffy-pancakes",
    name: "Fluffy Pancakes",
    emoji: "🥞",
    description: "Light and fluffy breakfast pancakes, golden on both sides.",
    servings: 2,
    time: "20 min",
    difficulty: "Easy",
    ingredients: [
      { name: "All-purpose flour", quantity: "1 cup" },
      { name: "Baking powder", quantity: "2 tsp" },
      { name: "Sugar", quantity: "2 tbsp" },
      { name: "Salt", quantity: "1/4 tsp" },
      { name: "Milk", quantity: "3/4 cup" },
      { name: "Egg", quantity: "1" },
      { name: "Melted butter", quantity: "2 tbsp" },
      { name: "Butter for the pan", quantity: "as needed" },
    ],
    steps: [
      { ingredient: "Flour + baking powder + sugar + salt", quantity: "1 cup + 2 tsp + 2 tbsp + 1/4 tsp", placement: "In a large bowl", action: "Whisk the dry ingredients together.", duration: "1 min" },
      { ingredient: "Milk + egg + melted butter", quantity: "3/4 cup + 1 + 2 tbsp", placement: "In a separate bowl", action: "Whisk the wet ingredients until combined.", duration: "1 min" },
      { ingredient: "Wet mixture", quantity: "All of it", placement: "Pour into the dry ingredients", action: "Stir just until combined — a few lumps are fine. Do not overmix.", duration: "1 min" },
      { ingredient: "Butter", quantity: "a little", placement: "Onto a pan over medium heat", action: "Melt and spread to coat the surface.", duration: "1 min" },
      { ingredient: "Batter", quantity: "1/4 cup per pancake", placement: "Onto the hot pan", action: "Cook until bubbles form on top and edges look set.", duration: "2 min" },
      { ingredient: "Pancake", quantity: "1", placement: "Flip in the pan", action: "Cook the other side until golden brown.", duration: "1 min" },
      { ingredient: "Pancakes", quantity: "All of them", placement: "Stack on a plate", action: "Serve warm with syrup, honey or fruit.", duration: "30 sec" },
    ],
  },
];

// Expose globally for the classic-script setup used by index.html.
window.RECIPES = RECIPES;
