(function () {
  "use strict";

  const MASTER = {
    recipes: [
      {
        name: "Confit Garlic",
        ingredients: [
          { item: "Peeled Garlic", amount: "50 gm" },
          { item: "Olive Oil", amount: "100 gm" },
          { item: "Rosemary", amount: "5 gm" },
          { item: "Black Pepper", amount: "2 gm" },
        ],
        instructions: [
          "Add the peeled garlic cloves to a small saucepan.",
          "Pour in olive oil until the garlic is fully submerged (approx. 100g). ",
          "Cook on lowest heat (do not boil) for 15 minutes until garlic is soft and lightly golden.",
          "Add rosemary.",
          "Let cool then grind garlic and oil together and store it airtight jar in the refrigerator.",
        ],
      },
      {
        name: "Hot Honey",
        ingredients: [
          { item: "Honey", amount: "50 gm" },
          { item: "Chilli Flakes", amount: "3 gm" },
          { item: "Apple Cider Vinegar", amount: "5 gm" },
          { item: "Water", amount: "10 gm" },
        ],
        instructions: [
          "In a small pan, add honey and chili flakes.",
          "Gently heat on low for 2–3 minutes. Do not boil. ",
          "Turn off the heat and stir in apple cider vinegar. ",
          "Let it steep for 5–10 minutes.",
          "Strain (optional) for a smooth texture or keep the flakes in.-Store it in clean container in refrigerator.",
        ],
      },
      {
        name: "Thecha Sauce",
        ingredients: [
          { item: "Roasted Green Chilli", amount: "100 gm" },
          { item: "Garlic", amount: "30 gm" },
          { item: "Peanut", amount: "50 gm" },
          { item: "Coriander", amount: "100 gm" },
          { item: "Jeera", amount: "20 gm" },
          { item: "Sunflower Oil", amount: "50 gm" },
          { item: "Salt", amount: "5 gm" },
        ],
        instructions: [
          "Wash the green chillies.",
          "Remove the top ends of all chillies.",
          "Switch on the induction at 1000 power.",
          "Light roast the peanuts.",
          "Put the roasted the peanuts in ceramic plate.",
          "Put the chillies in pan and roast the chillies for 5 mins",
          "Put the chillies in another plate.",
          "Let the chillies and peanuts cool down.",
          "In the meanwhile clean the corriander.",
          "Grinder the peanuts using the small grinder.",
          "Put the grinded peanuts in plate.",
          "Now grind the jeera.",
          "Put garlic in the same grinder.",
          "Add salt and chilli in the same grinder. ",
          "Add the grounded peanuts and grind everything together.",
          "Add oil in the grinder and mix everything together.",
          "Take out the theecha in clean container.",
          "Store it in the fridge.",
        ],
      },
      {
        name: "Garlic Butter",
        ingredients: [
          { item: "Butter", amount: "85 gm" },
          { item: "Garlic", amount: "10 gm" },
          { item: "Parsley", amount: "5 gm" },
          { item: "Salt", amount: "2 gm" },
          { item: "Pepper", amount: "3 gm" },
        ],
        instructions: [
          "Take the butter out of refrigirator.",
          "Take teh required butter in a plate and let it soften at room temp.",
          "Grind the garlic cloves.",
          "In a bowl combine softened butter with the garlic paste.",
          "Mix in parsley.",
          "Add salt to it.",
          "Add black pepper.",
          "Store in an airtight container.",
          "Store it refrigerate.",
        ],
      },
      {
        name: "Tandoori Paneer",
        ingredients: [
          { item: "Malia Paneer", amount: "500 gm" },
          { item: "Sunflower Oil", amount: "30 gm" },
          { item: "Mirchi Powder", amount: "7 gm" },
          { item: "Ginger Garlic Paste", amount: "20 gm" },
          { item: "Garam Masala", amount: "3 gm" },
          { item: "Salt", amount: "5 gm" },
          { item: "Kasuri Methi", amount: "2 gm" },
          { item: "Lemon Juice", amount: "15 gm" },
          { item: "Curd", amount: "100 gm" },
        ],
        instructions: [
          "Take paneer.",
          "Cut it in small cubes.",
          "Take a sauce pan and put on induction at 1000 power.",
          "Add oil in the pan.",
          "Add red chilli powder.",
          "Add Garam masala.",
          "Add ginger garlic paste.",
          "Add salt.",
          "Take kasuri methi in hand and press it between the palms.",
          "Add the kasuri meethi to the paneer.",
          "Mix everything well.",
          "Switch off the induction and wait for 5 mins.",
          "Now add curd and mix everything well.",
          "Tandoori paneer is ready.",
        ],
      },
      {
        name: "Mushroom Patty",
        ingredients: [
          { item: "Roasted Mushroom", amount: "220 gm" },
          { item: "White Onion", amount: "50 gm" },
          { item: "Garlic", amount: "10 gm" },
          { item: "Oregano", amount: "1 gm" },
          { item: "Breadcrumbs", amount: "25 gm" },
          { item: "Processed Cheese", amount: "20 gm" },
          { item: "Salt", amount: "15 gm" },
          { item: "Peri-Peri", amount: "15 gm" },
        ],
        instructions: [
          "Sauté garlic and onions in oil until soft.",
          "Add mushrooms and cook until all moisture evaporates (very important). ",
          "Let the mixture cool slightly.",
          "Mix everything together.",
          "Add breadcrumbs.",
          "Add grated cheese.",
          "Add pealed potato.",
          "Add salt, pepper, and herbs.",
          "Mix well until it holds shape. ",
          "Add more crumbs if too wet.",
          "Each patty of 70 gm.",
        ],
      },
      {
        name: "Coleslaw",
        ingredients: [
          { item: "Cabbage", amount: "50 gm" },
          { item: "Carrot", amount: "20 gm" },
          { item: "Apple", amount: "15 gm" },
          { item: "Mayonnaise", amount: "25 gm" },
          { item: "Salt", amount: "1 gm" },
          { item: "Black Pepper", amount: "1 gm" },
          { item: "Lemon Juice", amount: "1 gm" },
        ],
        instructions: [
          "Chop Carrot in vertical fine slices",
          "Chop Cabbage in vertical fine slices",
          "Chop Apple in vertical fine slices",
          "Combine all vegetables in a bowl.",
          "In a separate bowl take Mayo.",
          "Add salt to mayo.",
          "Add Lemon juice.",
          "Whisk everything together.",
          "Add the chopped veggies to the dressing. ",
          "Store the coleslaw in a clean container.",
          "Store it in the refrigirator.",
        ],
      },
      {
        name: "Pickled Red Cabbage",
        ingredients: [
          { item: "Red cabbage", amount: "50 gm" },
          { item: "White Vinegar", amount: "25 gm" },
          { item: "Water", amount: "25 gm" },
          { item: "Salt", amount: "2 gm" },
          { item: "Sugar", amount: "20 gm" },
          { item: "Black Peppercorn", amount: "1 gm" },
        ],
        instructions: [
          "Thinly slice the red Cabbage and place in a clean jar.",
          "Switch on the induction at 1000 power.",
          "Take a small pan.",
          "Add vinegar.",
          "Add water.",
          "Add sugar.",
          "Add salt.",
          "Stir until sugar and salt dissolve. ",
          "Remove from heat.",
          "Pour the hot mixture over the cabbage.",
          "Let cool to room temperature and then refrigerate in a clean container.",
        ],
      },
      {
        name: "Pickled Onion",
        ingredients: [
          { item: "Pickled Onion", amount: "50 gm" },
          { item: "White Vinegar", amount: "25 gm" },
          { item: "Water", amount: "25 gm" },
          { item: "Salt", amount: "2 gm" },
          { item: "Sugar", amount: "20 gm" },
          { item: "Black Pepper", amount: "1 gm" },
        ],
        instructions: [
          "Thinly slice the red Onions and place in a clean jar.",
          "Switch on the induction at 1000 power.",
          "Take a small pan.",
          "Add vinegar.",
          "Add water.",
          "Add sugar.",
          "Add salt.",
          "Stir until sugar and salt dissolve. ",
          "Remove from heat.",
          "Pour the hot mixture over the onions.",
          "Let cool to room temperature then refrigerate it in a clean container .",
        ],
      },
      {
        name: "Spicy Hummus",
        ingredients: [
          { item: "Chickpeas", amount: "150 gm" },
          { item: "Tahini", amount: "20 gm" },
          { item: "Garlic Chilli Sauce", amount: "30 gm" },
          { item: "Olive Oil", amount: "25 gm" },
          { item: "Ice Cubes (add ice while blending)", amount: "8 gm" },
          { item: "Salt", amount: "3 gm" },
        ],
        instructions: [
          "Soak the Chickpeas for 5 hours or overnight.",
          "Boil Chickpeas in cooker at 1000 power on induction.Wait till 5 whistles.",
          "Let the boiled Chickpeas cool down.",
          "Grind the boiled Chickpeas using a grinder and add ice while grinding.",
          "Make tahini using sesame seeds and water in the grinder.",
          "Take everything in a mixing bowl.",
          "Add chilli garlic sauce/paste as per the weight.",
          "Add olive oil in the grinder and grind things together.",
          "Blend until smooth, adding ice gradually to adjust texture.",
          "Add salt.",
          "Spicy hummus is ready.",
        ],
      },
      {
        name: "Thecha Korean Bun",
        ingredients: [
          { item: "Korean Bun", amount: "1" },
          { item: "Thecha", amount: "1gm (use measuring spoon)" },
          { item: "Cream Cheese", amount: "35 gm" },
          { item: "Mozzarella", amount: "5 gm" },
          { item: "Parsley", amount: "2 gm" },
          { item: "Salt", amount: "2 gm" },
          { item: "Pepper", amount: "2 gm" },
          { item: "Oregano", amount: "0.5" },
          { item: "Chilli Flakes", amount: "0.25" },
        ],
        instructions: [
          "Take cream cheese in a ceramic plate.",
          "Warm the cream cheese for 15 sec in microwave to soften it.",
          "Take mozzarella cheese in the same plate and warm it together for 10 sec.",
          "Take this mixture in mixing bowl.",
          "Add theecha.",
          "Add oregano.",
          "Add chilli flaxes.",
          "Add salt.",
          "Add pepper.",
          "Mix everything together.",
          "Take a piping bag.",
          "Fill mixture in a piping bag. ",
          "Cut the Piping bag slightly from the end before adding the mixture.",
          "Cut X shape into the bun without slicing through. There should be 8 cuts.",
          "Fill the bun with the mixture.",
          "Add chilli flaxes and organo.",
          "Add parley leaf in the center.",
          "Cover the bun with cling wrap and store it in freezer.",
        ],
      },
      {
        name: "Falafel",
        ingredients: [
          { item: "Soaked Chickpeas", amount: "250 gm" },
          { item: "Onion Rough Cut", amount: "75 gm" },
          { item: "Garlic", amount: "12 gm" },
          { item: "Coriander", amount: "20 gm" },
          { item: "Parsley", amount: "30 gm" },
          { item: "Cumin", amount: "4 gm" },
          { item: "Salt", amount: "6 gm" },
          { item: "Pepper", amount: "2 gm" },
          { item: "Baking Soda", amount: "1 gm" },
          { item: "Sesame Seed", amount: "5 gm" },
        ],
        instructions: [
          "Soak Chickpeas overnight (do not use canned).",
          "Drain thoroughly. ",
          "Take a grinder.",
          "Grind the Chickpeas till fine.",
          "Add ice cube to smoothen the paste.",
          "Take the grounded Chickpeas out in a bowl.",
          "Grind onion and garlic.",
          "Add parsley and grind again till everything is coarse but sticky.",
          "Take out the mixture in same bowl as Chickpeas.",
          "Add baking soda to the mixture.",
          "Mix everything well. ",
          "Store the falafel in a clean container in the refrigerator .",
        ],
      },
      {
        name: "Potato Masala Filling",
        ingredients: [
          { item: "Sunflower oil", amount: "8 gm" },
          { item: "Mustard Seed", amount: "3 gm" },
          { item: "Curry Leaf", amount: "2 gm" },
          { item: "Ginger", amount: "20 gm" },
          { item: "Green Chilli", amount: "15 gm" },
          { item: "Turmeric", amount: "3 gm" },
          { item: "Boiled Mash Potato", amount: "350 gm" },
          { item: "Salt", amount: "7 gm" },
          { item: "Coriander", amount: "7 gm" },
        ],
        instructions: [
          "Heat oil in a pan. Add mustard seeds and let them crackle.",
          "Add urad dal (if using), then curry leaves, green chilies, and ginger. ",
          "Add onions and sauté until soft and translucent.",
          "Add turmeric and mix well.",
          "Add boiled potatoes, salt, and a splash of water. Mix and mash lightly. ",
          "Cook for 3 to 4 minutes until well combined.",
          "Finish with lemon juice and chopped coriander.",
        ],
      },
      {
        name: "Mint Cilantro Sauce",
        ingredients: [
          { item: "Blanched Coriander", amount: "100 gm" },
          { item: "Green Chilli", amount: "1 chilli (1-3 gm)" },
          { item: "Mint Leaf Paste", amount: "25 gm" },
          { item: "Eggless Mayo", amount: "250 gm" },
          { item: "Lemon Juice", amount: "5 gm" },
          { item: "Salt", amount: "2 gm" },
        ],
        instructions: [
          "Take the grinder.",
          "Add the mint in the grinder and grind it into a paste form.",
          "Fine chop the coriander. ",
          "Then add the coriander and green chilli to the grinder .",
          "Grind everything together.",
          "In a mixing bowl add all prepared ingredients.",
          "Add the lemon juice.",
          "Add salt and mix everything together.",
          "Store in a squeeze bottle in the fridge for 3-4 days.",
        ],
      },
      {
        name: "Sriracha Schezwan Sauce",
        yield: "150 gm",
        ingredients: [
          { item: "Eggless Mayo", amount: "50 gm" },
          { item: "chilli garlic Sauce", amount: "50 gm" },
          { item: "Schezwan Sauce", amount: "50 gm" },
        ],
        instructions: [
          "Method:",
          "Take a weighing scale.",
          "Place a container on the weighing scale.",
          "Tear the weight.",
          "Add the mayo.",
          "Tear the weight.",
          "Add the Schezwan Sauce.",
          "Tear the weight.",
          "Add the Chilli garlic Sauce.",
          "Mix everything well.",
          "Store in a squeeze bottle and store in the fridge.",
          "Use within 3-4 days",
        ],
      },
      {
        name: "PESTO",
        ingredients: [
          { item: "Cleaned Basil Leaves", amount: "500 gms" },
          { item: "Garlic Peeled", amount: "50 gm" },
          { item: "Amul Cheese Cube", amount: "3 cubes" },
          { item: "Olive Oil", amount: "100 ml" },
          { item: "Walnuts", amount: "30 gm" },
          { item: "Salt", amount: "4 gm" },
          { item: "Black Pepper", amount: "2 gm" },
        ],
        instructions: [
          "Take all the basil leaves in a big contaner.",
          "Remove the steams from the leaves.",
          "Use the leaves only.",
          "Clean the basil leaves with water.",
          "Take the cheese cubes out of freezer.",
          "Put the cubes in hot water cup",
          "The the grinder and grind the basil leaves with little amount of water to make a thick paste.",
          "Take walnuts in the in the grinder and grind it in paste.",
          "Put the walnut paste in the grounded pesto.",
          "Grind the garlic in the grinder.",
          "Add some basil paste to the grinder and again grind it with garlic paste.",
          "Add the black pepper and salt and again grind it.",
          "Add the basil paste and grind it again.",
          "Add the 20 ml olive oil and grind it again.",
          "Take everything in the big container .",
          "Add the remaininh oil and mix everything together.",
        ],
      },
      {
        name: "Crumbles for Muffins",
        ingredients: [
          { item: "Maida", amount: "60 gm" },
          { item: "Sugar", amount: "100 gm" },
          { item: "Salt", amount: "2 gm" },
          { item: "Butter", amount: "56 gm" },
        ],
        instructions: [
          "Add Maida, Sugar and Salt in a bowl and whisk thoroughly",
          "Add butter and mix using hand, It will break down and form crumbles",
        ],
      },
      {
        name: "Samosa",
        ingredients: [
          { item: "Potato", amount: "500 gm" },
          { item: "Water", amount: "500 ml" },
          { item: "Maida", amount: "500 gm" },
          { item: "Ajwain", amount: "5 gm" },
          { item: "Salt", amount: "5 gm" },
          { item: "Oil", amount: "60 ml" },
          { item: "Cumin Seeds", amount: "5 gm" },
          { item: "Ginger", amount: "5 gm" },
          { item: "Hing (Asafoetida)", amount: "0.5 gm" },
          { item: "Green chilli (2 chillies)", amount: "5 gm" },
          { item: "Salt", amount: "2.5 gm" },
          { item: "Amchur Powder", amount: "2.5 gm" },
          { item: "Fennel Powder", amount: "2.5 ml" },
          { item: "Coriander leaves", amount: "5 gm" },
          { item: "Curry Leaves", amount: "5 gm" },
        ],
        instructions: [
          "Cut 3 to 4 medium Potatoes in half and pressure cook for 3 whistles",
          "Let them Cool and crumble them and keep aside.",
          "Switch on the induction.",
          "Put a frying pan.",
          "Add some oil to the pan.",
          "Once teh oil is heated add the cumin seeds.",
          "Add Hing.",
          "Add green chiili.",
          "Add Haldi.",
          "Add Coriander powder.",
          "In a mixing bowl take Maida.",
          "Add Ajwain to maid.",
          "Add the Salt.",
          "Add little Ghee.",
          "Serving Method",
        ],
      },
      {
        name: "Chocolate Ganache",
        ingredients: [
          { item: "Dark chocolate compound", amount: "150 gm" },
          { item: "Fresh Cream", amount: "200 gm" },
        ],
        instructions: [
          "Take 200 gm dark chocolate slab.",
          "Make small pieces of it.",
          "Melt the chocolate in microwave.",
          "Take 200 gram fresh cream in a cup/container.",
          "Melt the cream in microwave.",
          "Mix the melted chocolate and cream .",
          "Keep this ganache aside now.",
        ],
      },
      {
        name: "Brioche Bread",
        ingredients: [
          { item: "Maida", amount: "440 gm (3.5 cups)" },
          { item: "Yeast", amount: "12 gm (2.5 teaspoon)" },
          { item: "Salt", amount: "7 gm (1.5 teaspoon)" },
          { item: "Sugar", amount: "30 gm (1/4 Cup)" },
          { item: "Warm milk (38-40 degree celcius)", amount: "250 ml (1 cup)" },
          { item: "Yogurt / Milk Powder", amount: "30 ml ( 2 tablespoon)" },
          { item: "Milk If needed", amount: "30 ml ( 2 tablespoon)" },
        ],
        instructions: [
          "Mix flour, yeast, sugar, and salt in a large bowl.",
          "Add warm milk and yogurt. Mix until dough forms.",
          "Knead for 3-4 minutes, then gradually add butter 1 tbsp at a time. Continue kneading 8-10 minutes until smooth and elastic.",
          "Place in greased bowl, cover, and rise 1.5-2 hours until doubled.",
          "Shape into loaf or rolls. Place in greased 8x4 inch pan or molds.",
          "Cover and rise 45-60 minutes until dough rises above pan.",
          "Preheat oven to 180°C. Brush top with milk and bake 25-30 minutes for loaf or 18-20 minutes for rolls until golden.",
          "Cool on wire rack before slicing.",
        ],
      },
      {
        name: "Vara Pav Dry Chutney",
        ingredients: [
          { item: "Roasted Peanuts", amount: "50 gm" },
          { item: "Roasted Red chilli", amount: "3" },
          { item: "Chilli powder", amount: "2 gm" },
          { item: "jeera", amount: "15 gm" },
          { item: "Salt", amount: "3 gm" },
          { item: "Garlic", amount: "10 gm" },
        ],
        instructions: [
          "Take red chillies as per the weight mentioned.",
          "Remove the top ends of all chillies.",
          "Switch on the induction at 1000 power.",
          "Light roast the peanuts.",
          "Put the roasted the peanuts in ceramic plate.",
          "Put the chillies in pan and roast the chillies for 5 mins",
          "Put the chillies in another plate.",
          "Let the chillies and peanuts cool down.",
          "Grinder the peanuts using the small grinder.",
          "Put the grinded peanuts in plate.",
          "Now grind the jeera.",
          "Put garlic in the same grinder.",
          "Add salt and chilli in the same grinder. ",
          "Add the grounded peanuts and grind everything together.",
          "Add oil in the grinder and mix everything together.",
          "The vadapav dry chutney is ready.",
          "Store it in clean container in the shelves.",
        ],
      },
      {
        name: "BANANA WALNUT BREAD",
        ingredients: [
          { item: "Banana - Medium Ripe", amount: "4 pieces" },
          { item: "Olive oil", amount: "4 tbsp (4 tablespoon)\nOR 60 ml" },
          { item: "Lactose Free Milk OR Almond Milk (if Lactose free milk is not available)", amount: "180 ml\nor 12 tbsp\n(12 tablespoon)" },
          { item: "Honey", amount: "120 gm" },
          { item: "Walnuts ", amount: "25 gms" },
          { item: "Cinnamon Powder", amount: "1 tsp\n(1 teaspoon)\nOR 5 gm" },
          { item: "Baking Powder", amount: "1 tsp\n(1 teaspoon)\nOR 5 gm" },
          { item: "Baking Soda", amount: "1/2 tsp\n(half teaspoon)\nOR 2.5 gm" },
          { item: "Salt", amount: "2 pinch" },
          { item: "Ragi Atta   (Ragi Flour)", amount: "120 gm" },
          { item: "Jowar Atta   (Jowar Flour)", amount: "120 gm" },
        ],
        instructions: [
          "Smash all 4 Bananas using a fork in a plate.",
          "Transfer the smashed bananas in bowl.",
          "Add Olive Oil -  60 ml OR 4 Tablespoon.",
          "Add Lactose Free Milk  - 180 ml OR 12 Tablespoon\nOR Use Almond milk only if Lactose free milk is not available.",
          "Add Honey - 120 gm.",
          "Roughly chop the Walnuts - 25 gm.\n-Put half in the mixture. \n-Save Half for topping, before putting in oven.",
          "Add Cinnamon Powder - 1 tsp (1 teaspoon) OR 5 gm.",
          "Add Baking Powder - 1 tsp (1 teaspoon) OR 5 gm.",
          "Add Baking Soda - 1/2 tsp (Half teaspoon) OR 2.5 gm.",
          "Add Salt - 2 Pinch.",
          "Add Ragi Atta - 120 gm.",
          "Add Jowar Atta - 120 gm.",
          "Whisk the whole mixture using hand whisker.",
          "Take the Rectangular Bread Baking tray and apply butter using the butter brush.",
          "Use Non-Printed, Plain Butter Paper and put it on all inside walls of the baking tray and no tray should be visible.",
          "Apply more butter on the butter paper using butter brush.",
          "Transfer the whole mixture into the tray.",
          "Top it with remaining Walnuts (12 gms) and spread evenly across the mixture.",
          "Bake at 180 Degrees for 40 minutes.",
          "After 40 minutes - Insert a wooden stirrer in the bread and remove it.\n-If there is no residue on the stirrer, then Banana Walnut Bread is ready.\n-If there is residue sticking to the stirrer - then bake again for 10 minutes t 180 degrees. \n-Repeat process if necessary.\n",
          "Once Baked keep it at room temperature until it cools down post 1 Hour. ",
          "Remove loaf from the tray and Cut 1 inch slices.",
          "If there is space in undercounter, then keep the slices in the bread box in alluminium foil.",
          "If there is no space in undercounter - then cling wrap the bread slices tightly and store in Deep freezer",
        ],
      },
      {
        name: "Gucamole",
        ingredients: [
          { item: "Avacado", amount: "1/2" },
          { item: "onion", amount: "3 gm" },
          { item: "tomato", amount: "3 gm" },
          { item: "garlic clove", amount: "1" },
          { item: "salt", amount: "2 gm" },
          { item: "pepper", amount: "2 gm" },
        ],
        instructions: [
          "Steps to make guacamole:\n 1/2 avacado half and warm it for 30sec and smash it using fork.",
          "Fine chopped 2 gm tomato.",
          "Fine chopped 2 gm onion.",
          "Pinch of salt and pepper.",
          "Mix all the above together using fork and gucamole is ready.",
        ],
      },
      {
        name: "Almond Butter :",
        ingredients: [
          { item: "Butter", amount: "100 gm (softened butter)" },
          { item: "Maida", amount: "100 gm" },
          { item: "Powdered sugar", amount: "100 gm" },
          { item: "Almond flour", amount: "100 gm" },
        ],
        instructions: ["Mixx them well at room temp."],
      },
      {
        name: "Lotus Biscoff Soul Cake Spread",
        ingredients: [
          { item: "Hot Water", amount: "75 ml" },
          { item: "Normal Water", amount: "75 ml" },
          { item: "Lotus Biscoff Biscuit", amount: "1 packet" },
          { item: "Condensed Milk", amount: "45 ml" },
        ],
        instructions: [
          "Take hot water and normal water in the grinding pot.",
          "Add lotus biscoff biscuits in it.",
          "Add the condesned milk.",
        ],
      },
      {
        name: "New York Cheesecake",
        ingredients: [
          { item: "Cream Cheese", amount: "500 gm" },
          { item: "Milkmaid", amount: "220 gm" },
          { item: "Fresh Cream", amount: "200 gm" },
          { item: "Maida", amount: "20 gm" },
          { item: "Corn Flour", amount: "20 gm" },
          { item: "Vanilla Essence", amount: "5 gm" },
          { item: "Biscuits", amount: "8 pieces" },
        ],
        instructions: [
          "Base  \n Break 78 biscuits. Add butter and set in pan.\n Bake for 2 Minutes in microwave and then keep the pan fridge.\n\nCake \n Take cream cheese. Keep it in oven for 30 seconds. Repeat 30 seconds until it's soft like butter. Do not exceed 30 seconds.\n Add milkmaid, Fresh cream, maida, corn flour and Vanilla essence.\n Whisk it thoroughly till we get desired consistency. Approx 710 mins.\n Bake it in water bath for 35 min at 230 degree in OTG.\n\nServing   \n Check with guest  If they want it warm or cold?\n If cheesecake is freshly baked  Serve as it is.\n If Guest want warm, heat for 1015 seconds in microwave.\n If cheesecake is Cold/frozen  Heat for 1020 seconds until desired warmness or fluffiness.",
        ],
      },
      {
        name: "Burnt Basque Cheesecake",
        yield: "1200 gm",
        ingredients: [
          { item: "Cream Cheese", amount: "500 gm" },
          { item: "Milkmaid", amount: "150 gm" },
          { item: "Curd / Yogurt", amount: "60 gm" },
          { item: "Fresh Cream", amount: "200 gm" },
          { item: "Maida", amount: "20 gm" },
          { item: "Corn Flour", amount: "20 gm" },
          { item: "Vanilla Essence", amount: "5 gm" },
        ],
        instructions: [
          "Take a weighing scale.",
          "Take a ceramic plate.",
          "Take cream cheese and warm it up for 30 sec.Repeat 30 seconds until its soft like butter.",
          "Put the cream cheese in a mixing bowl.",
          "Add milkmaid.",
          "Add the Fresh cream.",
          "Add the maida.",
          "Add the corn flour.",
          "Add the Vanilla essence.",
          "Whisk it thoroughly till we get desired consistency. Approx 7-10 mins.",
          "Greece the tin with butter aqnd apply butter paper to it.",
          "Put the bater in the tin and place the tin in the otg.",
          "Bake for 35 min at 230 degree in OTG.",
        ],
      },
    ],
  };

  const SKIP = new Set([]);

  const EMOJI_RULES = [
    [/cheesecake|muffin|crumble/, "🍰"],
    [/ganache|chocolate/, "🍫"],
    [/honey/, "🍯"],
    [/butter/, "🧈"],
    [/paneer|cheese/, "🧀"],
    [/brioche|bread|bun/, "🍞"],
    [/pickled|cabbage|coleslaw|onion/, "🥬"],
    [/falafel|patty|samosa|potato|masala/, "🧆"],
    [/guacamole|avocado/, "🥑"],
    [/pesto|thecha|chutney|sauce|schezwan|hummus|cilantro/, "🥫"],
    [/garlic/, "🧄"],
  ];

  function slugify(value) {
    return String(value || "")
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");
  }

  function emojiFor(name) {
    const key = String(name || "").toLowerCase();
    for (const [pattern, emoji] of EMOJI_RULES) {
      if (pattern.test(key)) return emoji;
    }
    return "🫙";
  }

  function toRecipe(master) {
    return {
      id: "comp-" + slugify(master.name),
      name: master.name,
      emoji: emojiFor(master.name),
      description: "Base Recipe",
      category: "component",
      yield: master.yield || "",
      servings: 1,
      time: "",
      difficulty: "Easy",
      ingredients: (master.ingredients || []).map((ing) => ({
        name: ing.item,
        quantity: ing.amount,
      })),
      steps: (master.instructions || []).map((action) => ({
        ingredient: "",
        quantity: "",
        placement: "",
        action: action,
        duration: "",
      })),
    };
  }

  const COMPONENTS = MASTER.recipes
    .filter((master) => !SKIP.has(String(master.name).toLowerCase()))
    .map(toRecipe);

  const RECIPE_LINKS = {
    "confit garlic": "comp-confit-garlic",
    "hot honey": "comp-hot-honey",
    thecha: "comp-thecha-sauce",
    "garlic butter": "comp-garlic-butter",
    "tandoori paneer": "comp-tandoori-paneer",
    "tandoori paneer filling": "comp-tandoori-paneer",
    "mushroom patty": "comp-mushroom-patty",
    coleslaw: "comp-coleslaw",
    "pickled red cabbage": "comp-pickled-red-cabbage",
    "pickled cabbage": "comp-pickled-red-cabbage",
    "pickled onion": "comp-pickled-onion",
    "pickled red onion": "comp-pickled-onion",
    "spicy hummus": "comp-spicy-hummus",
    "spicy hummus dip": "comp-spicy-hummus",
    falafel: "comp-falafel",
    "potato masala filling": "comp-potato-masala-filling",
    "mint cilantro sauce": "comp-mint-cilantro-sauce",
    "cilantro mayo": "comp-mint-cilantro-sauce",
    "cilantro mayo dip": "comp-mint-cilantro-sauce",
    "mint mayo": "comp-mint-cilantro-sauce",
    "mint mayo sauce": "comp-mint-cilantro-sauce",
    "sriracha schezwan sauce": "comp-sriracha-schezwan-sauce",
    "sriracha schezwan dip": "comp-sriracha-schezwan-sauce",
    "schezwan sriracha dip": "comp-sriracha-schezwan-sauce",
    pesto: "comp-pesto",
    "pesto sauce": "comp-pesto",
    samosa: "comp-samosa",
    "chocolate ganache": "comp-chocolate-ganache",
    brioche: "comp-brioche-bread",
    "brioche bread": "comp-brioche-bread",
    "vada pav dry chutney": "comp-vara-pav-dry-chutney",
    "vada paav dry chutney": "comp-vara-pav-dry-chutney",
    "vara pav dry chutney": "comp-vara-pav-dry-chutney",
    guacamole: "comp-gucamole",
    gucamole: "comp-gucamole",
    "almond butter": "comp-almond-butter",
    "lotus biscoff sauce": "comp-lotus-biscoff-soul-cake-spread",
    "lotus biscoff spread": "comp-lotus-biscoff-soul-cake-spread",
    "thecha korean bun": "comp-thecha-korean-bun",
    "banana walnut bread": "comp-banana-walnut-bread",
    "new york cheesecake": "comp-new-york-cheesecake",
    "burnt basque cheesecake": "comp-burnt-basque-cheesecake",
  };

  window.COMPONENTS = COMPONENTS;
  window.RECIPE_LINKS = RECIPE_LINKS;
})();
