(function () {
  "use strict";

  function toSteps(actions) {
    return actions.map((action) => ({
      ingredient: "",
      quantity: "",
      placement: "",
      action: action,
      duration: "",
    }));
  }

  function ingredient(name, quantity) {
    return { name: name, quantity: quantity };
  }

  function hotSizes(size175, size250, size325) {
    return {
      hot: {
        "175ml": size175,
        "250ml": size250,
        "325ml": size325,
      },
    };
  }

  function coldSizes(size250, size325, size350) {
    return {
      cold: {
        "250ml": size250,
        "325ml": size325,
        "350ml": size350,
      },
    };
  }

  const SEASONAL_SPECIALS = [
    {
      id: "creamed-bee",
      name: "Creamed Bee",
      emoji: "🍯",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: false, cold: true },
      sizes: { "175ml": false, "250ml": true, "325ml": true, "350ml": true },
      ingredients: [
        ingredient("Whip Cream", "30 gm"),
        ingredient("Honey", "15 gm"),
        ingredient("Espresso for cold foam", "15 ml"),
        ingredient("Ice", "120 gm"),
        ingredient("Milk", "90 ml"),
        ingredient("Espresso for milk", "45 ml"),
      ],
      ingredientVariants: coldSizes(
        [
          ingredient("Whip Cream", "20 gm"),
          ingredient("Honey", "10 gm"),
          ingredient("Espresso for cold foam", "15 ml"),
          ingredient("Ice", "120 gm"),
          ingredient("Milk", "60 ml"),
          ingredient("Espresso for milk", "45 ml"),
        ],
        [
          ingredient("Whip Cream", "30 gm"),
          ingredient("Honey", "15 gm"),
          ingredient("Espresso for cold foam", "15 ml"),
          ingredient("Ice", "150 gm"),
          ingredient("Milk", "90 ml"),
          ingredient("Espresso for milk", "45 ml"),
        ],
        [
          ingredient("Whip Cream", "30 gm"),
          ingredient("Honey", "15 gm"),
          ingredient("Espresso for cold foam", "15 ml"),
          ingredient("Ice", "150 gm"),
          ingredient("Milk", "90 ml"),
          ingredient("Espresso for milk", "45 ml"),
        ]
      ),
      steps: toSteps([
        "Keep a cup on the weighing scale and tare to zero.",
        "Add Whipping Cream.",
        "Add Honey.",
        "Whisk using electric whisker. If too thick, add milk and whisk a little.",
        "Take a clean glass and add ice.",
        "Add Milk.",
        "Add a shot of espresso.",
        "Add honey cold foam slowly using inverted spoon to form a layer.",
      ]),
    },
    {
      id: "blue-awakening",
      name: "Blue Awakening",
      emoji: "💙",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: false, cold: true },
      sizes: { "175ml": false, "250ml": true, "325ml": true, "350ml": true },
      ingredients: [
        ingredient("Ice", "120 gm"),
        ingredient("Tonic Water", "140 ml"),
        ingredient("Espresso", "45 ml"),
        ingredient("Blue Curacao", "21 ml"),
      ],
      ingredientVariants: coldSizes(
        [
          ingredient("Ice", "100 gm"),
          ingredient("Tonic Water", "100 ml"),
          ingredient("Espresso", "30 ml"),
          ingredient("Blue Curacao", "15 ml"),
        ],
        [
          ingredient("Ice", "120 gm"),
          ingredient("Tonic Water", "140 ml"),
          ingredient("Espresso", "45 ml"),
          ingredient("Blue Curacao", "21 ml"),
        ],
        [
          ingredient("Ice", "140 gm"),
          ingredient("Tonic Water", "140 ml"),
          ingredient("Espresso", "45 ml"),
          ingredient("Blue Curacao", "21 ml"),
        ]
      ),
      steps: toSteps([
        "Pull out an espresso shot.",
        "Take a clean glass and add ice to it.",
        "Add Tonic water slowly.",
        "Add the espresso shot that was pulled earlier.",
        "Measure the Blue Curacao syrup using a 30 60.",
        "Add the syrup on top of espresso using an inverted spoon to form a layer.",
        "Serve with a straw.",
      ]),
    },
    {
      id: "bombon",
      name: "Bombon",
      emoji: "🍫",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: false, cold: true },
      sizes: { "175ml": false, "250ml": true, "325ml": true, "350ml": true },
      ingredients: [
        ingredient("Espresso", "45 ml"),
        ingredient("Condensed Milk", "30 ml"),
        ingredient("Ice", "120 gm"),
      ],
      ingredientVariants: coldSizes(
        [
          ingredient("Espresso", "30 ml"),
          ingredient("Condensed Milk", "20 ml"),
          ingredient("Ice", "100 gm"),
        ],
        [
          ingredient("Espresso", "45 ml"),
          ingredient("Condensed Milk", "30 ml"),
          ingredient("Ice", "120 gm"),
        ],
        [
          ingredient("Espresso", "45 ml"),
          ingredient("Condensed Milk", "30 ml"),
          ingredient("Ice", "140 gm"),
        ]
      ),
      steps: toSteps([
        "Pull out an espresso shot.",
        "Take a clean glass.",
        "Put the glass on the weighing scale.",
        "Add condensed milk as per measure.",
        "Add espresso shot.",
        "Mix everything together.",
        "Ask if customer wants ice, then add it.",
      ]),
    },
    {
      id: "purple-sunset",
      name: "Purple Sunset",
      emoji: "🌅",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: false, cold: true },
      sizes: { "175ml": false, "250ml": true, "325ml": true, "350ml": true },
      ingredients: [
        ingredient("4 pm Purple Tea Leaves", "0.5 gm or 2 teaspoons"),
        ingredient("Hot water", "20 ml"),
        ingredient("Tonic Water", "90 ml"),
        ingredient("Orange Juice", "30 ml"),
        ingredient("Ice", "100 gm"),
      ],
      ingredientVariants: coldSizes(
        [
          ingredient("4 pm Purple Tea Leaves", "0.5 gm or 2 teaspoons"),
          ingredient("Hot water", "20 ml"),
          ingredient("Tonic Water", "90 ml"),
          ingredient("Orange Juice", "30 ml"),
          ingredient("Ice", "100 gm"),
        ],
        [
          ingredient("4 pm Purple Tea Leaves", "0.5 gm or 2 teaspoons"),
          ingredient("Hot water", "20 ml"),
          ingredient("Tonic Water", "90 ml"),
          ingredient("Orange Juice", "30 ml"),
          ingredient("Ice", "120 gm"),
        ],
        [
          ingredient("4 pm Purple Tea Leaves", "0.5 gm or 2 teaspoons"),
          ingredient("Hot water", "20 ml"),
          ingredient("Tonic Water", "90 ml"),
          ingredient("Orange Juice", "30 ml"),
          ingredient("Ice", "140 gm"),
        ]
      ),
      steps: toSteps([
        "Take 30 ml warm water.",
        "Take 5 gm 4 pm purple tea leaves and add it to the warm water for brewing.",
        "Take a clean glass.",
        "Add ice to the glass.",
        "Using 30 60 measure the orange juice.",
        "Add the orange juice at the bottom of the glass.",
        "Measure the tonic water using 30 60.",
        "Add tonic water using a spoon to make layer.",
        "Strain the tea and add it to the glass with help of spoon to make a layer.",
        "Serve with a straw.",
      ]),
    },
    {
      id: "citrus-sunrise",
      name: "Citrus Sunrise",
      emoji: "🍊",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: false, cold: true },
      sizes: { "175ml": false, "250ml": true, "325ml": true, "350ml": true },
      ingredients: [
        ingredient("Ice", "120 gm"),
        ingredient("Orange Juice", "45 ml"),
        ingredient("Tonic Water", "135 ml"),
        ingredient("Espresso", "45 ml"),
      ],
      ingredientVariants: coldSizes(
        [
          ingredient("Ice", "100 gm"),
          ingredient("Orange Juice", "30 ml"),
          ingredient("Tonic Water", "90 ml"),
          ingredient("Espresso", "30 ml"),
        ],
        [
          ingredient("Ice", "120 gm"),
          ingredient("Orange Juice", "45 ml"),
          ingredient("Tonic Water", "135 ml"),
          ingredient("Espresso", "45 ml"),
        ],
        [
          ingredient("Ice", "140 gm"),
          ingredient("Orange Juice", "45 ml"),
          ingredient("Tonic Water", "135 ml"),
          ingredient("Espresso", "45 ml"),
        ]
      ),
      steps: toSteps([
        "Pull an espresso shot.",
        "Take a clean glass.",
        "Add ice to the glass.",
        "Using 30 60 measure the orange juice.",
        "Add the orange juice at the bottom of the glass.",
        "Measure the tonic water using 30 60.",
        "Add tonic water using a spoon to make layer.",
        "Add the espresso to the glass with help of spoon to make a layer.",
        "Serve with a straw.",
      ]),
    },
    {
      id: "apple-crumble-pie-latte-iced",
      name: "Apple Crumble Pie Latte Iced",
      emoji: "🍏",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: false, cold: true },
      sizes: { "175ml": false, "250ml": true, "325ml": true, "350ml": true },
      ingredients: [
        ingredient("Apple Crumble Pie Syrup", "45 ml"),
        ingredient("Espresso", "45 ml"),
        ingredient("Milk", "135 ml"),
        ingredient("Ice", "125 gm"),
        ingredient("Cream Cheese", "15 gm"),
        ingredient("Whipping Cream", "45 gm"),
      ],
      ingredientVariants: coldSizes(
        [
          ingredient("Apple Crumble Pie Syrup", "30 ml"),
          ingredient("Espresso", "30 ml"),
          ingredient("Milk", "90 ml"),
          ingredient("Ice", "100 gm"),
          ingredient("Cream Cheese", "10 gm"),
          ingredient("Whipping Cream", "30 gm"),
        ],
        [
          ingredient("Apple Crumble Pie Syrup", "45 ml"),
          ingredient("Espresso", "45 ml"),
          ingredient("Milk", "135 ml"),
          ingredient("Ice", "125 gm"),
          ingredient("Cream Cheese", "15 gm"),
          ingredient("Whipping Cream", "45 gm"),
        ],
        [
          ingredient("Apple Crumble Pie Syrup", "45 ml"),
          ingredient("Espresso", "45 ml"),
          ingredient("Milk", "150 ml"),
          ingredient("Ice", "140 gm"),
          ingredient("Cream Cheese", "15 gm"),
          ingredient("Whipping Cream", "45 gm"),
        ]
      ),
      steps: toSteps([
        "Keep a cup on the weighing scale and tare to zero.",
        "Add Whipping Cream.",
        "Add cream cheese.",
        "Add 15 ml espresso.",
        "Add Apple crumble pie syrup.",
        "Whisk using electric whisker. If too thick, add milk and whisk a little.",
        "Take a clean glass and add ice.",
        "Add Milk.",
        "Add a shot of espresso.",
        "Add cold foam slowly using inverted spoon to form a layer.",
      ]),
    },
    {
      id: "salted-caramel-mocha",
      name: "Salted Caramel Mocha",
      emoji: "🍫",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: true, cold: false },
      sizes: { "175ml": true, "250ml": true, "325ml": false, "350ml": true },
      ingredients: [
        ingredient("Espresso", "45 ml"),
        ingredient("Milk", "165 ml"),
        ingredient("Caramel Sauce", "15 ml"),
        ingredient("Chocolate Sauce", "15 ml"),
        ingredient("Salt", "3 Dashes"),
        ingredient("Ice", "120 gm"),
      ],
      ingredientVariants: hotSizes(
        [
          ingredient("Espresso", "30 ml"),
          ingredient("Milk", "90 ml"),
          ingredient("Caramel Sauce", "15 ml"),
          ingredient("Chocolate Sauce", "10 ml"),
          ingredient("Salt", "2 Dashes")
        ],
        [
          ingredient("Espresso", "45 ml"),
          ingredient("Milk", "165 ml"),
          ingredient("Caramel Sauce", "15 ml"),
          ingredient("Chocolate Sauce", "15 ml"),
          ingredient("Salt", "3 Dashes")
        ],
        [
          ingredient("Espresso", "60 ml"),
          ingredient("Milk", "240 ml"),
          ingredient("Caramel Sauce", "15 ml"),
          ingredient("Chocolate Sauce", "20 ml"),
          ingredient("Salt", "3 Dashes")
        ]
      ),
      steps: toSteps([
        "Pull an espresso shot.",
        "Add chocolate syrup.",
        "Add caramel syrup.",
        "Mix it all together.",
        "Take a clean glass.",
        "Add ice to the glass.",
        "Add milk.",
        "Add chocolate sauce on the glass on sides.",
        "Add the espresso shot mix.",
        "Serve it with straw.",
      ]),
    },
    {
      id: "mont-blanc",
      name: "Mont Blanc",
      emoji: "🍊",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: false, cold: true },
      sizes: { "175ml": false, "250ml": true, "325ml": true, "350ml": true },
      ingredients: [
        ingredient("Ice", "120 gm"),
        ingredient("Orange Juice", "30 ml"),
        ingredient("Cold Brew", "120 ml"),
        ingredient("Whip Cream", "45 ml"),
        ingredient("Vanilla Syrup", "15 ml"),
        ingredient("Orange Juice", "15 ml"),
      ],
      ingredientVariants: coldSizes(
        [
          ingredient("Ice", "100 gm"),
          ingredient("Orange Juice", "15 ml"),
          ingredient("Cold Brew", "60 ml"),
          ingredient("Whip Cream", "15 ml"),
          ingredient("Vanilla Syrup", "15 ml"),
          ingredient("Orange Juice", "15 ml"),
        ],
        [
          ingredient("Ice", "100 gm"),
          ingredient("Orange Juice", "30 ml"),
          ingredient("Cold Brew", "120 ml"),
          ingredient("Whip Cream", "45 ml"),
          ingredient("Vanilla Syrup", "15 ml"),
          ingredient("Orange Juice", "15 ml"),
        ],
        [
          ingredient("Ice", "120 gm"),
          ingredient("Orange Juice", "30 ml"),
          ingredient("Cold Brew", "120 ml"),
          ingredient("Whip Cream", "45 ml"),
          ingredient("Vanilla Syrup", "15 ml"),
          ingredient("Orange Juice", "15 ml"),
        ]
      ),
      steps: toSteps([
        "Keep a shaker on the weighing scale and tare to zero.",
        "Add Whipping Cream.",
        "Add Vanilla Syrup.",
        "Add Orange Juice.",
        "Whisk Thoroughly using electric whisker.",
        "Add ice.",
        "Add Orange Juice.",
        "Add Cold Brew.",
        "Shake the shaker.",
        "Take a clean glass and pour the drink in it.",
        "Serve with a straw.",
      ]),
    },
    {
      id: "peppermint-mocha",
      name: "Peppermint Mocha",
      emoji: "🍫",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: true, cold: false },
      sizes: { "175ml": true, "250ml": true, "325ml": false, "350ml": true },
      ingredients: [
        ingredient("Cool Green Ocean Tea", "0.5 gm"),
        ingredient("Hot Water", "10 ml"),
        ingredient("Espresso", "45 ml"),
        ingredient("Milk", "180 ml"),
        ingredient("Chocolate", "22 ml")
      ],
      ingredientVariants: hotSizes(
        [
          ingredient("Cool Green Ocean Tea", "0.5 gm"),
          ingredient("Hot Water", "10 ml"),
          ingredient("Espresso", "30 ml"),
          ingredient("Milk", "120 ml"),
          ingredient("Chocolate", "15 ml")
        ],
        [
          ingredient("Cool Green Ocean Tea", "0.5 gm"),
          ingredient("Hot Water", "10 ml"),
          ingredient("Espresso", "45 ml"),
          ingredient("Milk", "180 ml"),
          ingredient("Chocolate", "22 ml")
        ],
        [
          ingredient("Cool Green Ocean Tea", "0.5 gm"),
          ingredient("Hot Water", "10 ml"),
          ingredient("Espresso", "60 ml"),
          ingredient("Milk", "240 ml"),
          ingredient("Chocolate", "30 ml")
        ]
      ),
      steps: toSteps([
        "Take 30 ml warm milk.",
        "Take 5 gm cool green ocean tea leaves and add it to the warm water for brewing.",
        "Pull the espresso shot.",
        "Take a weighing scale.",
        "Put the espresso shot glass on it.",
        "Tare the weight.",
        "Add chocolate sauce as per measure and mix it well.",
        "Take a clean glass.",
        "Add ice in the glass.",
        "Add the brewed milk in the glass.",
        "Add the espresso shot.",
      ]),
    },
    {
      id: "Double-Coffee-Cold-Brew-Cascarra",
      name: "Double Coffee (Cold Brew Cascarra)",
      emoji: "☕",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: false, cold: true },
      sizes: { "175ml": false, "250ml": true, "325ml": true, "350ml": true },
      ingredients: [
        ingredient("Espresso", "45 ml"),
        ingredient("Sugar", "8 ml"),
        ingredient("Cascara", "20 ml"),
        ingredient("Tonic water", "140 ml"),
        ingredient("Ice", "120 gm"),
      ],
      ingredientVariants: coldSizes(
        [
          ingredient("Espresso", "30 ml"),
          ingredient("Sugar", "5 ml"),
          ingredient("Cascara", "15 ml"),
          ingredient("Tonic water", "100 ml"),
          ingredient("Ice", "100 gm"),
        ],
        [
          ingredient("Espresso", "45 ml"),
          ingredient("Sugar", "8 ml"),
          ingredient("Cascara", "20 ml"),
          ingredient("Tonic water", "140 ml"),
          ingredient("Ice", "120 gm"),
        ],
        [
          ingredient("Espresso", "45 ml"),
          ingredient("Sugar", "8 ml"),
          ingredient("Cascara", "20 ml"),
          ingredient("Tonic water", "140 ml"),
          ingredient("Ice", "140 gm"),
        ]
      ),
      steps: toSteps([
        "Pull out a shot of espresso.",
        "Add sugar and mix. This becomes our Coffee Syrup.",
        "Take a clean glass and add ice.",
        "Add tonic water slowly.",
        "Add cascara.",
        "Add espresso shot that was mixed with sugar earlier.",
      ]),
    },
    {
      id: "Sparkling-Cascara-Tonic-Water-Cascara",
      name: "Sparkling Cascara (Tonic Water Cascara)",
      emoji: "🥤",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: false, cold: true },
      sizes: { "175ml": false, "250ml": true, "325ml": true, "350ml": true },
      ingredients: [
        ingredient("Tonic Water", "140 ml"),
        ingredient("Sugar Syrup", "8 ml"),
        ingredient("Lemon", "6-7 drops"),
        ingredient("Mint", "6 leaves"),
        ingredient("Cascara brew", "40 ml"),
        ingredient("Ice", "120 gm"),
      ],
      ingredientVariants: coldSizes(
        [
          ingredient("Tonic Water", "100 ml"),
          ingredient("Sugar Syrup", "5 ml"),
          ingredient("Lemon", "4-5 drops"),
          ingredient("Mint", "4 leaves"),
          ingredient("Cascara brew", "30 ml"),
          ingredient("Ice", "100 gm"),
        ],
        [
          ingredient("Tonic Water", "140 ml"),
          ingredient("Sugar Syrup", "8 ml"),
          ingredient("Lemon", "6-7 drops"),
          ingredient("Mint", "6 leaves"),
          ingredient("Cascara brew", "40 ml"),
          ingredient("Ice", "120 gm"),
        ],
        [
          ingredient("Tonic Water", "140 ml"),
          ingredient("Sugar Syrup", "8 ml"),
          ingredient("Lemon", "6-7 drops"),
          ingredient("Mint", "6 leaves"),
          ingredient("Cascara brew", "40 ml"),
          ingredient("Ice", "140 gm"),
        ]
      ),
      steps: toSteps([
        "Collect lemon, mint leaves, sugar syrup and cascara in one place.",
        "Take a clean glass and add ice.",
        "Add tonic water slowly.",
        "Add sugar syrup.",
        "Add lemon drops.",
        "Add cascara using an inverted spoon to form a brown cascara layer on top of white tonic water.",
        "Smash mint leaves and add on top.",
      ]),
    },
    {
      id: "Blue-Pea-Tea-Iced-Latte",
      name: "Blue Pea Tea Iced Latte",
      emoji: "🧋",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: false, cold: true },
      sizes: { "175ml": false, "250ml": true, "325ml": true, "350ml": true },
      ingredients: [
        ingredient("Water", "40 ml"),
        ingredient("Milk", "75 ml"),
        ingredient("Whip Cream", "45 gm"),
        ingredient("Espresso", "45 ml"),
        ingredient("Ice", "120 gm"),
        ingredient("Blue Pea Tea Flowers", "0.5 gm or 3 teaspoons"),
      ],
      ingredientVariants: coldSizes(
        [
          ingredient("Water", "30 ml"),
          ingredient("Milk", "  60 ml"),
          ingredient("Whip Cream", "30 gm"),
          ingredient("Espresso", "30 ml"),
          ingredient("Ice", "100 gm"),
          ingredient("Blue Pea Tea Flowers", "0.25 gm or 2 teaspoons"),
        ],
        [
          ingredient("Water", "40 ml"),
          ingredient("Milk", "75 ml"),
          ingredient("Whip Cream", "45 gm"),
          ingredient("Espresso", "45 ml"),
          ingredient("Ice", "120 gm"),
          ingredient("Blue Pea Tea Flowers", "0.5 gm or 3 teaspoons"),
        ],
        [
          ingredient("Water", "40 ml"),
          ingredient("Milk", "75 ml"),
          ingredient("Whip Cream", "45 gm"),
          ingredient("Espresso", "45 ml"),
          ingredient("Ice", "140 gm"),
          ingredient("Blue Pea Tea Flowers", "0.5 gm or 3 teaspoons"),
        ]
      ),
      steps: toSteps([
        "Brew Blue Pea Tea Flowers in hot water in a French Press for 3 minutes.",
        "In a cup, take milk and add Blue Pea Tea Concoction using a filter. The milk will turn blue.",
        "Pull out a shot of espresso.",
        "Keep another cup on weighing scale and add Whipping cream.",
        "Add Espresso Shot and milk in the cup with whipping cream and whisk using electric whisker to form a cold foam.",
        "Take Ice in a clean glass.",
        "Add the blue milk we prepared, in the glass.",
        "Top up with Espresso Cold Foam using inverted spoon to form a layer. Serve immediately.",
      ]),
    },
    {
      id: "Tiramisu-Iced-Latte",
      name: "Tiramisu Iced Latte",
      emoji: "🍰",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: false, cold: true },
      sizes: { "175ml": false, "250ml": true, "325ml": true, "350ml": true },
      ingredients: [
        ingredient("Whip Cream", "45 gm"),
        ingredient("Milk", "90 ml"),
        ingredient("Tiramisu Syrup of cold foam", "22 ml"),
        ingredient("Espresso", "45 ml"),
        ingredient("Ice", "120 gm"),
        ingredient("Tiramisu Syrup for milk", "10 ml"),
        ingredient("Coco Powder", "1 dash"),
        ingredient("Ladyfinger Biscuit (Tiramisu Biscuit)", "1"),
      ],
      ingredientVariants: coldSizes(
        [
          ingredient("Whip Cream", "30 gm"),
          ingredient("Milk", "60 ml"),
          ingredient("Tiramisu Syrup of cold foam", "15 ml"),
          ingredient("Espresso", "30 ml"),
          ingredient("Ice", "100 gm"),
          ingredient("Tiramisu Syrup for milk", "7.5 ml"),
          ingredient("Coco Powder", "1 dash"),
          ingredient("Ladyfinger Biscuit (Tiramisu Biscuit)", "1"),
        ],
        [
          ingredient("Whip Cream", "45 gm"),
          ingredient("Milk", "90 ml"),
          ingredient("Tiramisu Syrup of cold foam", "22 ml"),
          ingredient("Espresso", "45 ml"),
          ingredient("Ice", "120 gm"),
          ingredient("Tiramisu Syrup for milk", "10 ml"),
          ingredient("Coco Powder", "1 dash"),
          ingredient("Ladyfinger Biscuit (Tiramisu Biscuit)", "1"),
        ],
        [
          ingredient("Whip Cream", "45 gm"),
          ingredient("Milk", "90 ml"),
          ingredient("Tiramisu Syrup of cold foam", "22 ml"),
          ingredient("Espresso", "45 ml"),
          ingredient("Ice", "140 gm"),
          ingredient("Tiramisu Syrup for milk", "10 ml"),
          ingredient("Coco Powder", "1 dash"),
          ingredient("Ladyfinger Biscuit (Tiramisu Biscuit)", "1"),
        ]
      ),
      steps: toSteps([
        "Place a cup on weighing scale and tare to zero.",
        "Add Whipping Cream.",
        "Add Milk.",
        "Add Tiramisu Syrup.",
        "Whisk using electric whisker to form Tiramisu Cold Foam.",
        "Pull out an espresso shot.",
        "Take a Clean Glass and add Ice.",
        "Add Milk.",
        "Add Tiramisu Syrup.",
        "Slowly add Tiramisu Cold Foam using inverted spoon to form a top layer.",
        "Dust Coco Powder on top.",
        "Keep a Ladyfinger Biscuit (Tiramisu Biscuit) on top.",
      ]),
    },
    {
      id: "Vietnamese-shakerato",
      name: "Vietnamese Shakerato",
      emoji: "🥤",
      description: "Iced Drink",
      category: "special-drinks",
      drinkType: "iced",
      servings: 1,
      time: "5 min",
      difficulty: "Medium",
      temperatures: { hot: false, cold: true },
      sizes: { "175ml": false, "250ml": true, "325ml": true, "350ml": true },
      ingredients: [
        ingredient("Ice", "120 gm"),
        ingredient("Condensed Milk", "45 gm"),
        ingredient("Espresso", "90 ml"),
        ingredient("Milk", "60 ml"),
        ingredient("Cinnamon powder", "3 dash"),
        ingredient("Mint", "6 leaves"),
      ],
      ingredientVariants: coldSizes(
        [
          ingredient("Ice", "100 gm"),
          ingredient("Condensed Milk", "30 gm"),
          ingredient("Espresso", "60 ml"),
          ingredient("Milk", "60 ml"),
          ingredient("Cinnamon powder", "2 dash"),
          ingredient("Mint", "4 leaves"),
        ],
        [
          ingredient("Ice", "120 gm"),
          ingredient("Condensed Milk", "45 gm"),
          ingredient("Espresso", "90 ml"),
          ingredient("Milk", "60 ml"),
          ingredient("Cinnamon powder", "3 dash"),
          ingredient("Mint", "6 leaves"),
        ],
        [
          ingredient("Ice", "140 gm"),
          ingredient("Condensed Milk", "45 gm"),
          ingredient("Espresso", "90 ml"),
          ingredient("Milk", "60 ml"),
          ingredient("Cinnamon powder", "3 dash"),
          ingredient("Mint", "6 leaves"),
        ]
      ),
      steps: toSteps([
        "Pull out an espresso shot but do not add in the shaker yet.",
        "Take the Bar Shaker and put it on weighing scale. Set the weight to zero (Tare).",
        "Add Condensed Milk in the shaker by weight (gm).",
        "Measure milk in 'ml' and Add in the shaker.",
        "Take Mint leaves, smash them by hand, break them and add in the shaker.",
        "Add Cinnamon powder from the box - Tap the box from behind aiming at the shaker.",
        "Add Espresso shot in the shaker.",
        "Add ice in the shaker.",
        "Close the lid tightly and Shake the contents well.",
        "Pour in a clean glass from the smaller lid of shaker.",
        "Remove the share cap and pour rest of the drink in the glass.",
      ]),
    },
    {
      id: "soul-signature-cold-brew",
      name: "Soul Signature Cold Brew",
      emoji: "✨",
      description: "Soul Special",
      category: "drinks",
      drinkType: "soul-special",
      servings: 1,
      time: "5 min",
      difficulty: "Easy",
      ingredients: [
        { name: "Cold brew concentrate", quantity: "120 ml" },
        { name: "Water", quantity: "80 ml" },
        { name: "Vanilla syrup", quantity: "15 ml" },
        { name: "Ice cubes", quantity: "5" },
        { name: "Orange peel", quantity: "1" },
      ],
      steps: toSteps([
        "Fill a glass with ice cubes.",
        "Pour in the cold brew concentrate and water.",
        "Add the vanilla syrup and stir.",
        "Twist an orange peel over the top and drop it in.",
        "Serve chilled.",
      ]),
    },
    {
      id: "winter-spiced-mocha",
      name: "Winter Spiced Mocha",
      emoji: "✨",
      description: "Soul Special",
      category: "drinks",
      drinkType: "soul-special",
      servings: 1,
      time: "8 min",
      difficulty: "Easy",
      ingredients: [
        { name: "Espresso", quantity: "1 shot" },
        { name: "Steamed milk", quantity: "160 ml" },
        { name: "Dark chocolate", quantity: "20 gm" },
        { name: "Cinnamon", quantity: "1 pinch" },
        { name: "Nutmeg", quantity: "1 pinch" },
      ],
      steps: toSteps([
        "Melt the dark chocolate into the hot espresso.",
        "Steam the milk with a pinch of cinnamon.",
        "Combine the milk with the chocolate espresso.",
        "Dust with nutmeg and serve warm.",
      ]),
    },
  ];

  window.SEASONAL_SPECIALS = SEASONAL_SPECIALS;
})();
